### ISSUE TITLE
Process list of images sequentially

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [neat-web/SelfieSegmentation#1]
Hi, thank you for this useful project, I'm trying to remove the background from a list of images, the code below works but the image being processed randomly e.g. the 5th image processed first instead of 1 then the 60th image...

I'm using **`AsyncTask`** 
```
 @Override
    protected String doInBackground(String... str) {
    for (File file : files) {
        segmenter.process(InputImage.fromBitmap(ImageUtils.getBitmap(file), 0))
                .addOnSuccessListener(segmentationMask -> {
                    maskBuffer = segmentationMask.getBuffer();
                    maskWidth = segmentationMask.getWidth();
                    maskHeight = segmentationMask.getHeight();
                    addFrame(segmentHelper.generateMaskBgImage(ImageUtils.getBitmap(file),
                            transparentBitmap,
                            maskBuffer,
                            maskWidth,
                            maskHeight));
                });

    }
   ....
   }
```

**Comment by neat-web** [comment]
Hello, I am glad you found the example useful. An `AsyncTask` or some background `Thread` looks like a good choice for your requirement. I have not tried it out, but `process (InputImage image)` returns a `Task<SegmentationMask>` itself. Maybe you can use some synchronization, or store a processed image in an array at its intended position?
